version: '2'

services:
  postfix:
    image: instrumentisto/postfix:3
    volumes:
    - ./config/postfix:/etc/postfix/main.cf.d
    - ./config/mailman-core:/opt/mailman
    ports:
    - 25:25
    networks:
      mailman:
        ipv4_address: 172.19.199.1

  mailman-core:
    image: maxking/mailman-core:0.2
    volumes:
    - ./config/mailman-core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - SMTP_HOST=172.19.199.1
    - HYPERKITTY_API_KEY=someapikey
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.2
    depends_on:
    - database
    links:
    - mailman-core
    - database
    - postfix
    volumes:
    - ./config/mailman-web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SERVE_FROM_DOMAIN=lists.fablab-karlsruhe.de
    - SECRET_KEY=supersecretdjangokey
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    ports:
    - 80:8000
    networks:
      mailman:
        ipv4_address: 172.19.199.3

  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 172.19.199.4

networks:
  mailman:
    ipam:
      config:
        - subnet: 172.19.199.0/24
