version: '2'

services:
  postfix:
    image: tozd/postfix:alpine-38
    volumes:
    - ./config/postfix:/etc/service/postfix
    - ./config/mailman-core:/opt/mailman
    - ./data/postfix:/var/spool/postfix
    environment:
    - MAILNAME=lists.fablab-karlsruhe.de
    - MY_DESTINATION='localhost.localdomain, localhost, lists.fablab-karlsruhe.de'
    - MY_NETWORKS='172.19.199.0/16 127.0.0.0/8'
    - ROOT_ALIAS=mail@morbi-happens.de
    ports:
    - 25:25
    networks:
      mailman:
        ipv4_address: 172.19.199.1

  mailman-core:
    image: maxking/mailman-core:0.2
    volumes:
    - ./config/mailman-core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - SMTP_HOST=postfix
    - HYPERKITTY_API_KEY=someapikey
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.2
    depends_on:
    - database
    links:
    - mailman-core
    - database
    - postfix
    volumes:
    - ./config/mailman-web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SERVE_FROM_DOMAIN=lists.fablab-karlsruhe.de
    - SECRET_KEY=supersecretdjangokey
    networks:
      mailman:
        ipv4_address: 172.19.199.3

  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    restart: always
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    networks:
      mailman:
        ipv4_address: 172.19.199.4

networks:
  mailman:
    ipam:
      config:
        - subnet: 172.19.199.0/16
